"""initial schema

Revision ID: 2b1e4ce95a11
Revises: 
Create Date: 2026-04-08 10:38:05.687116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b1e4ce95a11'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuits',
    sa.Column('circuit_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('track_length_km', sa.Float(), nullable=False),
    sa.Column('pit_loss_seconds', sa.Float(), nullable=False),
    sa.Column('overtake_difficulty', sa.Float(), nullable=False),
    sa.Column('drs_zones', sa.Integer(), nullable=False),
    sa.Column('drying_rate_coeff', sa.Float(), nullable=False),
    sa.Column('sector_distances', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('circuit_id')
    )
    op.create_table('races',
    sa.Column('race_id', sa.String(length=50), nullable=False),
    sa.Column('circuit_id', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('total_laps', sa.Integer(), nullable=False),
    sa.Column('fastf1_session_key', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.circuit_id'], ),
    sa.PrimaryKeyConstraint('race_id')
    )
    op.create_table('driver_entries',
    sa.Column('entry_id', sa.String(length=50), nullable=False),
    sa.Column('race_id', sa.String(length=50), nullable=False),
    sa.Column('driver_id', sa.String(length=10), nullable=False),
    sa.Column('driver_name', sa.String(length=100), nullable=False),
    sa.Column('team_id', sa.String(length=50), nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('team_color', sa.String(length=7), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=False),
    sa.Column('grid_position', sa.Integer(), nullable=False),
    sa.Column('finish_position', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('points_scored', sa.Float(), nullable=False),
    sa.Column('base_pace_seconds', sa.Float(), nullable=True),
    sa.Column('fuel_corrected_pace', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['races.race_id'], ),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_index('ix_driver_entries_race_driver', 'driver_entries', ['race_id', 'driver_id'], unique=False)
    op.create_table('race_events',
    sa.Column('event_id', sa.String(length=60), nullable=False),
    sa.Column('race_id', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('lap_start', sa.Integer(), nullable=False),
    sa.Column('lap_end', sa.Integer(), nullable=False),
    sa.Column('trigger_driver_id', sa.String(length=10), nullable=True),
    sa.Column('details', sa.String(length=500), nullable=True),
    sa.Column('penalty_seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['races.race_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_race_events_race_laps', 'race_events', ['race_id', 'lap_start', 'lap_end'], unique=False)
    op.create_table('scenarios',
    sa.Column('scenario_id', sa.String(length=50), nullable=False),
    sa.Column('race_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('pit_overrides', sa.JSON(), nullable=True),
    sa.Column('event_overrides', sa.JSON(), nullable=True),
    sa.Column('weather_overrides', sa.JSON(), nullable=True),
    sa.Column('driver_overrides', sa.JSON(), nullable=True),
    sa.Column('race_param_overrides', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['races.race_id'], ),
    sa.PrimaryKeyConstraint('scenario_id')
    )
    op.create_table('surface_states',
    sa.Column('state_id', sa.String(length=60), nullable=False),
    sa.Column('race_id', sa.String(length=50), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('surface_water_mm', sa.Float(), nullable=False),
    sa.Column('grip_scalar', sa.Float(), nullable=False),
    sa.Column('valid_compound_class', sa.String(length=20), nullable=False),
    sa.Column('tyre_deg_temp_modifier', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['races.race_id'], ),
    sa.PrimaryKeyConstraint('state_id')
    )
    op.create_index('ix_surface_race_lap', 'surface_states', ['race_id', 'lap_number'], unique=False)
    op.create_table('weather_samples',
    sa.Column('sample_id', sa.String(length=60), nullable=False),
    sa.Column('race_id', sa.String(length=50), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('air_temp_celsius', sa.Float(), nullable=False),
    sa.Column('track_temp_celsius', sa.Float(), nullable=False),
    sa.Column('humidity_percent', sa.Float(), nullable=False),
    sa.Column('wind_speed_ms', sa.Float(), nullable=False),
    sa.Column('wind_direction_deg', sa.Float(), nullable=False),
    sa.Column('rainfall_intensity_mm_hr', sa.Float(), nullable=False),
    sa.Column('is_raining', sa.Boolean(), nullable=False),
    sa.Column('pressure_mbar', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['races.race_id'], ),
    sa.PrimaryKeyConstraint('sample_id')
    )
    op.create_index('ix_weather_race_lap', 'weather_samples', ['race_id', 'lap_number'], unique=False)
    op.create_table('laps',
    sa.Column('lap_id', sa.String(length=60), nullable=False),
    sa.Column('entry_id', sa.String(length=50), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('lap_time_seconds', sa.Float(), nullable=True),
    sa.Column('sector1_seconds', sa.Float(), nullable=True),
    sa.Column('sector2_seconds', sa.Float(), nullable=True),
    sa.Column('sector3_seconds', sa.Float(), nullable=True),
    sa.Column('tyre_compound', sa.String(length=20), nullable=False),
    sa.Column('tyre_age', sa.Integer(), nullable=False),
    sa.Column('fuel_load_kg', sa.Float(), nullable=True),
    sa.Column('is_pit_in_lap', sa.Boolean(), nullable=False),
    sa.Column('is_pit_out_lap', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('gap_to_leader_seconds', sa.Float(), nullable=True),
    sa.Column('interval_seconds', sa.Float(), nullable=True),
    sa.Column('is_under_sc', sa.Boolean(), nullable=False),
    sa.Column('is_under_vsc', sa.Boolean(), nullable=False),
    sa.Column('is_personal_best', sa.Boolean(), nullable=False),
    sa.Column('speed_trap_kmh', sa.Float(), nullable=True),
    sa.Column('track_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['driver_entries.entry_id'], ),
    sa.PrimaryKeyConstraint('lap_id')
    )
    op.create_index('ix_laps_entry_lap', 'laps', ['entry_id', 'lap_number'], unique=False)
    op.create_index('ix_laps_lap_number', 'laps', ['lap_number'], unique=False)
    op.create_table('pit_stops',
    sa.Column('pit_id', sa.String(length=60), nullable=False),
    sa.Column('entry_id', sa.String(length=50), nullable=False),
    sa.Column('stop_number', sa.Integer(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('stop_duration_seconds', sa.Float(), nullable=False),
    sa.Column('pit_lane_duration_seconds', sa.Float(), nullable=False),
    sa.Column('tyre_compound_from', sa.String(length=20), nullable=False),
    sa.Column('tyre_compound_to', sa.String(length=20), nullable=False),
    sa.Column('was_under_sc', sa.Boolean(), nullable=False),
    sa.Column('was_under_vsc', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['driver_entries.entry_id'], ),
    sa.PrimaryKeyConstraint('pit_id')
    )
    op.create_table('sim_results',
    sa.Column('result_id', sa.String(length=50), nullable=False),
    sa.Column('scenario_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('computation_time_ms', sa.Integer(), nullable=False),
    sa.Column('simulated_laps', sa.JSON(), nullable=False),
    sa.Column('finish_order', sa.JSON(), nullable=False),
    sa.Column('position_history', sa.JSON(), nullable=False),
    sa.Column('diff_summary', sa.JSON(), nullable=False),
    sa.Column('key_divergence_lap', sa.Integer(), nullable=True),
    sa.Column('narrative', sa.String(length=2000), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.scenario_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sim_results')
    op.drop_table('pit_stops')
    op.drop_index('ix_laps_lap_number', table_name='laps')
    op.drop_index('ix_laps_entry_lap', table_name='laps')
    op.drop_table('laps')
    op.drop_index('ix_weather_race_lap', table_name='weather_samples')
    op.drop_table('weather_samples')
    op.drop_index('ix_surface_race_lap', table_name='surface_states')
    op.drop_table('surface_states')
    op.drop_table('scenarios')
    op.drop_index('ix_race_events_race_laps', table_name='race_events')
    op.drop_table('race_events')
    op.drop_index('ix_driver_entries_race_driver', table_name='driver_entries')
    op.drop_table('driver_entries')
    op.drop_table('races')
    op.drop_table('circuits')
    # ### end Alembic commands ###
